### ISSUE TITLE
Structuring and Cleaning Data

### ISSUE THREAD

**Issue by Soumi0911** [CapstoneProject18/Twitter-Hashtag-Analysis#1]
As a developer, I require only some information from the dataset, like user’s profile information, tweet
content with hashtags and tweet date &amp; time, so take out only these information and
structure the dataset.
Acceptance criteria:
- It is difficult for me to analyse the whole raw dataset as it takes huge time to
process, so I have to take out only relevant information out of whole dataset.
- Extract profile information, tweet content with hashtags and tweet date &amp; time.
- I need to structure the filtered dataset and save it on the disk.

**Comment by renuka24502** [comment]
Successfully completed
