### ISSUE TITLE
Analyse via Date Function

### ISSUE THREAD

**Issue by lavkushsingh31** [CapstoneProject18/Twitter-Hashtag-Analysis#11]
As a User, after successful login, in order to get the output of how much my hashtag is trending, I can
provide input as hashtag along with the required date between which the analysis should
occur.

Acceptance Criteria:

- When I click on the Analyse via date button on the home page, a page opens up that
require two date fields as input.
- I must provide an input to “From Date” and “To Date” fields.
- When I click on analyse button, I get the options to view the results in various
formats.

**Comment by renuka24502** [comment]
Successfully Completed
