### ISSUE TITLE
Analyse Function via Graph

### ISSUE THREAD

**Issue by hiteshyadav13** [CapstoneProject18/Twitter-Hashtag-Analysis#13]
As a logged in user, when I am on analyse function page and submit hashtag or date along with it as input, I should be able to get option to visualize the results graphically.

Acceptance Criteria:
- When I am on either of the pages, analyse via keyword or Analyse via date, I can click on analyse button after giving appropriate input.
- As soon as I click on analyse button, I get the options to view the results either in tabular form or graphical.
- When I choose to view results graphically, i can see and interpret the graph to make inference.

**Comment by renuka24502** [comment]
Successfully Completed
