### ISSUE TITLE
Security Implementation

### ISSUE THREAD

**Issue by Rishabhkandoi** [CapstoneProject18/Twitter-Hashtag-Analysis#16]
As a developer, in order to provide security to the website, I must implement SSL on the website hosting.

Acceptance Criteria:
i.	I must host the website on a server from the local machine.
ii.	I have to add a layer of SSL while hosting the website URL on the server.
iii.	I am now able to see that the URL of the hosted website contains “https” instead of “http”.
iv.	I am now assured that the website is secured and safe to be used.

**Comment by renuka24502** [comment]
Successfully Completed
