### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by renuka24502** [CapstoneProject18/Twitter-Hashtag-Analysis#17]
As a developer, In order to provide stable and optimized version of the software, I must test the product in different environments with different inputs to see whether the software is able to fulfill the requirements of the user at each point of time or not.

Acceptance Criteria:
- I must test whether my product is giving output in short time span or not.
- I should be able to get the same result of the same input irrespective of the environment in which the software is running.
- I should test the limit of number of users that can access the website at the same time simultaneously.
- I should provide proper warning message in case the input is out of the domain.

**Comment by lavkushsingh31** [comment]
Implemented Successfully. Done.
