### ISSUE TITLE
Processing Data set

### ISSUE THREAD

**Issue by hiteshyadav13** [CapstoneProject18/Twitter-Hashtag-Analysis#2]
As a developer, I need to process data set so that I am able to provide analysis on hashtags and provide top users contributing to the trending of hashtag.

Acceptance Criteria:
- I have to write python code to analyse data set to work on hashtags and associated users.
- The constraint of time involved in giving the output of data analysis has to be kept in mind for smoother and faster analysis.

**Comment by renuka24502** [comment]
Successfully completed
