### ISSUE TITLE
Retrieving Raw Data

### ISSUE THREAD

**Issue by lavkushsingh31** [CapstoneProject18/Twitter-Hashtag-Analysis#3]
As a Developer, in order to get dataset, I need to extract raw data from twitter, which consists of all tweets
and re-tweets.

Acceptance Criteria:

- To be able to access twitter raw data, I require to create a twitter developer
account.
- I need to write python code to retrieve raw data from twitter.
- Save the raw data to local disk for processing purpose.

**Comment by Rishabhkandoi** [comment]
Completed
