### ISSUE TITLE
Data Visualization

### ISSUE THREAD

**Issue by Rishabhkandoi** [CapstoneProject18/Twitter-Hashtag-Analysis#5]
As a developer, I need to provide the user with the graphical or tabular output of the hashtag analysis so that the user can get the better understanding of the results required.
As a user, i can view the result of the analysis either via graphically or table.

Acceptance Criteria:
- Generate graphical or tabular results of the outputs generated.
- Use appropriate tools to integrate the results to be verified visually by the user.

**Comment by renuka24502** [comment]
Successfully Completed
