### ISSUE TITLE
Forgot Password Function

### ISSUE THREAD

**Issue by hiteshyadav13** [CapstoneProject18/Twitter-Hashtag-Analysis#8]
As a user, I must be able to retrieve my credentials if somehow I am unable to login.

Acceptance Criteria:
- If I forgot password that I created at the time of registration, I can click on forgot password button on the login page.
- On the forgot password page, I must provide registered email-id and click on submit.
- I would get a verification mail on the given email-id.
- When I click on the verification link, I get the option to create a new password.
- I have to enter new password and submit.
- The new password along with the username can now be used to login.

**Comment by renuka24502** [comment]
Successfully Completed
